### ISSUE TITLE
Use Ambari API wrapper instead of curl ?

### ISSUE THREAD

**Issue by IDerr** [adaltas/jumbo#11]
Hi, 
I saw that you're using curl to start services which add a dependency if you are not using Linux.
Why not using the ambari client for python ?
https://github.com/jimbobhickville/python-ambariclient

Source:
https://github.com/adaltas/jumbo/blob/5a4ad60fb1dcd33b7ac0a3df7c44d5c5efea8e67/jumbo/core/vagrant.py#L49

**Comment by RReivax** [comment]
This part has been changed recently (on `dev` branch). Now we call a playbook for service startup (https://github.com/adaltas/jumbo/blob/a06b9699e5e9ae807bf0082dead14eaece14ca00/jumbo/core/data/playbooks/start-services.yml)
The ansible dependency has been moved to the host (not installed in a VM anymore). The curl part is being handled by ansible `uri` module, which might need to be replaced by `win_uri` for Windows. Otherwise, we can just make the API calls from a VM to avoid this issue.

**Comment by wdavidw** [comment]
While we wrote ryba, 97% of the commands where run from the targeted node through SSH. One day, I arrive to a customer where the only open access to the cluster was SSH, with the impossibility to install anything like jumbo nor ryba on the cluster and I got stuck. I quickly rewrote the two nikita modules which where doing http and ldap request from the host machine and considered since then that no command must be issued from the host machine.
