### ISSUE TITLE
SSL version causes Ambari-agent failure

### ISSUE THREAD

**Issue by WIN32GG** [adaltas/jumbo#12]
After launching a test cluster with

> jumbo  > create testcluster -t small-full
> jumbo (testcluster) > start

the ambari-agent logs showed:

> ERROR 2019-02-13 17:03:13,563 NetUtil.py:96 - EOF occurred in violation of protocol (_ssl.c:618)
ERROR 2019-02-13 17:03:13,563 NetUtil.py:97 - SSLError: Failed to connect. Please check openssl library versions. 

and nodes did not appear.

This can be fixed by adding:
> [security]
> force_https_protocol=PROTOCOL_TLSv1_2

in

> /etc/ambari-agent/conf/ambari-agent.ini

**Comment by RReivax** [comment]
Thank you @WIN32GG, this is fixed for version 0.5 currently on `dev` branch ( https://github.com/adaltas/jumbo/blob/dev/jumbo/core/data/jumbo-services/playbooks/roles/ambariagents/tasks/main.yml#L16 )

Closing.

**Comment by nulijiushimeili** [comment]
> After launching a test cluster with
> 
> > jumbo  > create testcluster -t small-full
> > jumbo (testcluster) > start
> 
> the ambari-agent logs showed:
> 
> > ERROR 2019-02-13 17:03:13,563 NetUtil.py:96 - EOF occurred in violation of protocol (_ssl.c:618)
> > ERROR 2019-02-13 17:03:13,563 NetUtil.py:97 - SSLError: Failed to connect. Please check openssl library versions.
> 
> and nodes did not appear.
> 
> This can be fixed by adding:
> 
> > [security]
> > force_https_protocol=PROTOCOL_TLSv1_2
> 
> in
> 
> > /etc/ambari-agent/conf/ambari-agent.ini

When I add the property 
`[security]
force_https_protocol=PROTOCOL_TLSv1_2
`
 in
`
/etc/ambari-agent/conf/ambari-agent.ini
`
I got a  another error :
`
Failed to connect to https://ndsc01:8440/ca due to 'module' object has no attribute 'PROTOCOL_TLSv1_2'  
WARNING 2020-04-25 18:54:47,471 NetUtil.py:124 - Server at https://ndsc01:8440 is not reachable, sleeping for 10 seconds...
`
